Repository funny-nation/Funny-Nation, pull requests merged in 2022-07, with the labels that each got.

#125 Dev
  CONTRIBUTING.md
  docs/developer-guides.md
  src/bot.ts
  src/client.ts
  src/discord-token.ts
  src/features/create-user-and-add-money-exp/index.ts
  src/features/get-user-member-profile/index.ts
  src/features/mumble/index.ts
  src/features/set-commands.ts
  src/features/set-guild-profile/config-admin-role/index.ts
  src/features/set-guild-profile/config-language-and-timezone/close-button-listener.ts
  src/features/set-guild-profile/config-language-and-timezone/factories/get-language-setting-message-action-row.ts
  src/features/set-guild-profile/config-language-and-timezone/factories/get-time-zone-setting-message-action-row.ts
  src/features/set-guild-profile/config-language-and-timezone/factories/index.ts
  src/features/set-guild-profile/config-language-and-timezone/menu-creater-listener.ts
  src/features/set-guild-profile/config-language-and-timezone/menu-listener.ts
  src/features/setup-commands-when-bot-start-and-join-guild/index.ts
  src/features/transfer-coin/index.ts
  src/language/README.md
  src/language/chinese-simple.ts
  src/language/english.ts
  src/language/get-language.ts
  src/language/index.d.ts
  src/language/index.ts
  src/language/language.ts
  src/logger.ts
  src/models/db-coin-transfer/add-db-coin-transfer.ts
  src/models/db-coin-transfer/db-coin-transfer.ts
  src/models/db-coin-transfer/index.ts
  src/models/db-guild/db-guild.ts
  src/models/db-guild/get-db-guild.ts
  src/models/db-guild/index.ts
  src/models/db-member/db-member.d.ts
  src/models/db-member/db-member.ts
  src/models/db-member/get-db-member.ts
  src/models/db-member/index.ts
  src/models/db-user/db-user.ts
  src/models/db-user/get-db-user.ts
  src/models/db-user/index.ts
  src/models/enum/index.ts
  src/models/enum/language-enum.ts
  src/models/enum/transfer-category.ts
  src/models/index.ts
  src/prisma-client.ts
  src/utils/command-setup.ts
  src/utils/index.ts
  src/utils/is-admin.ts
  src/utils/is-test.ts
Labels: enhancement

#130 A lot of things
  .eslintrc.json
  prisma/migrations/20220727073326_add_new_transfer_category_earn_from_voice/migration.sql
  prisma/schema.prisma
  src/client.ts
  src/features/add-coins-exp-to-user-in-voice/README.md
  src/features/add-coins-exp-to-user-in-voice/coin-exp-adder.ts
  src/features/add-coins-exp-to-user-in-voice/index.ts
  src/features/add-coins-exp-to-user-in-voice/put-user-in-voice-into-storage-when-init.ts
  src/features/add-coins-exp-to-user-in-voice/users-in-voice-storage.ts
  src/features/add-coins-exp-to-user-in-voice/voice-update-controller.ts
  src/features/create-user-and-add-coins-exp/README.md
  src/features/create-user-and-add-coins-exp/index.ts
  src/features/get-user-member-profile/index.ts
  src/features/index.ts
  src/features/set-guild-profile/config-others/close-button-listener.ts
  src/features/set-guild-profile/config-others/menu-creater-listener.ts
  src/features/set-guild-profile/config-others/menu-listener.ts
  src/features/transfer-coin/modal-controller.ts
  src/language/chinese-simplified.ts
  src/language/english.ts
  src/language/language.ts
  src/models/db-coin-transfer/add-db-coin-transfer.ts
  src/models/db-user/db-user.ts
  src/models/enum/index.d.ts
  src/models/enum/language-enum.d.ts
  src/models/enum/transfer-category.d.ts
Labels: bug

#134 Send Notification by Super User
  README.md
  package-lock.json
  src/client.ts
  src/features/index.ts
  src/features/super-user-commands/factory/get-super-user-notification-modal.ts
  src/features/super-user-commands/get-modal-by-commands.ts
  src/features/super-user-commands/index.ts
  src/features/super-user-commands/notification-submittion-listener/index.ts
  src/features/super-user-commands/notification-submittion-listener/notification-demo-handler.ts
  src/features/super-user-commands/notification-submittion-listener/notification-send-handler.ts
  src/features/super-user-commands/setup-command.ts
  src/features/super-user-commands/super-user-id-from-env.ts
  src/language/chinese-simplified.ts
  src/language/english.ts
  src/language/language.ts
  src/utils/get-notification-channel-by-guild.ts
  src/utils/index.ts
Labels: documentation, enhancement

#137 Add feature of leaderboard
  src/features/anonymous-msg/send-anonymous-msg-from-modal.ts
  src/features/get-user-member-profile/index.ts
  src/features/get-user-member-profile/render-exp-bar.ts
  src/features/get-user-member-profile/tests/render-exp-bar.test.ts
  src/features/index.ts
  src/features/leader-board/commands.ts
  src/features/leader-board/index.ts
  src/features/leader-board/listen-on-leaderboard.ts
  src/language/chinese-simplified.ts
  src/language/english.ts
  src/language/language.ts
  src/models/index.ts
  src/models/leader-board/index.ts
  src/models/leader-board/leader-board.ts
  src/utils/calculate-level-by-exp.ts
  src/utils/index.ts
  src/utils/tests/calculate-level-by-exp.test.ts
Labels: enhancement
